import * as client from "openid-client";
import { Strategy } from "openid-client/passport";
import passport from "passport";
import session from "express-session";
import memoize from "memoizee";
import connectPg from "connect-pg-simple";
import { storage } from "./storage.js";

const getOidcConfig = memoize(
  async () => {
    return await client.discovery(
      new URL(process.env.ISSUER_URL ?? "https://replit.com/oidc"),
      process.env.REPL_ID
    );
  },
  { maxAge: 3600 * 1000 }
);

// Shared frontend origin calculation
// This function determines the correct frontend origin for OAuth callbacks and CORS
// Follows Replit guidelines: use REPLIT_DEV_DOMAIN for dev, REPLIT_DOMAINS for production, FRONTEND_ORIGIN env var, or localhost:5000 fallback
export function getFrontendOrigin() {
  if (process.env.REPLIT_DEV_DOMAIN) {
    return `https://${process.env.REPLIT_DEV_DOMAIN}`;
  } else if (process.env.REPLIT_DOMAINS) {
    // REPLIT_DOMAINS is comma-separated in production (e.g., "sanchopoetry.com,www.sanchopoetry.com,...")
    // Use the first domain for OAuth callbacks
    const firstDomain = process.env.REPLIT_DOMAINS.split(',')[0].trim();
    return `https://${firstDomain}`;
  } else if (process.env.FRONTEND_ORIGIN) {
    return process.env.FRONTEND_ORIGIN;
  } else {
    return 'http://localhost:5000';
  }
}

export function getSession() {
  // Validate required environment variables
  if (!process.env.SESSION_SECRET) {
    throw new Error(
      'SESSION_SECRET must be set. This is auto-generated by Replit but must be configured for sessions to work.'
    );
  }

  if (!process.env.DATABASE_URL) {
    throw new Error(
      'DATABASE_URL must be set. Sessions require a database connection.'
    );
  }

  const sessionTtl = 7 * 24 * 60 * 60 * 1000; // 1 week
  const pgStore = connectPg(session);
  const sessionStore = new pgStore({
    conString: process.env.DATABASE_URL,
    createTableIfMissing: true, // Auto-create sessions table if missing
    ttl: sessionTtl,
    tableName: "sessions",
  });
  const isProduction = process.env.NODE_ENV === 'production';
  return session({
    secret: process.env.SESSION_SECRET,
    store: sessionStore,
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: isProduction, // Only secure in production (HTTPS)
      maxAge: sessionTtl,
    },
  });
}

function updateUserSession(user, tokens) {
  user.claims = tokens.claims();
  user.access_token = tokens.access_token;
  user.refresh_token = tokens.refresh_token;
  user.expires_at = user.claims?.exp;
}

async function upsertUser(claims) {
  await storage.upsertUser({
    id: claims["sub"],
    email: claims["email"],
    firstName: claims["first_name"],
    lastName: claims["last_name"],
    profileImageUrl: claims["profile_image_url"],
  });
}

export async function setupAuth(app) {
  app.set("trust proxy", 1);
  app.use(getSession());
  app.use(passport.initialize());
  app.use(passport.session());

  const config = await getOidcConfig();
  
  // Use shared frontend origin for OAuth callbacks
  const frontendOrigin = getFrontendOrigin();
  
  console.log("Frontend origin for OAuth:", frontendOrigin);

  const verify = async (tokens, verified) => {
    const user = {};
    updateUserSession(user, tokens);
    await upsertUser(tokens.claims());
    verified(null, user);
  };

  // Keep track of registered strategies
  const registeredStrategies = new Set();

  // Helper function to ensure strategy exists for a domain
  const ensureStrategy = (req) => {
    const host = req.get('host'); // Gets hostname:port (e.g., localhost:5000)
    const strategyName = `replitauth:${host}`;
    if (!registeredStrategies.has(strategyName)) {
      const strategy = new Strategy(
        {
          name: strategyName,
          config,
          scope: "openid email profile offline_access",
          callbackURL: `${frontendOrigin}/api/callback`,
        },
        verify,
      );
      passport.use(strategy);
      registeredStrategies.add(strategyName);
    }
  };

  passport.serializeUser((user, cb) => cb(null, user));
  passport.deserializeUser((user, cb) => cb(null, user));

  app.get("/api/login", (req, res, next) => {
    ensureStrategy(req);
    const host = req.get('host');
    passport.authenticate(`replitauth:${host}`, {
      prompt: "login consent",
      scope: ["openid", "email", "profile", "offline_access"],
    })(req, res, next);
  });

  app.get("/api/callback", (req, res, next) => {
    ensureStrategy(req);
    const host = req.get('host');
    passport.authenticate(`replitauth:${host}`, (err, user) => {
      if (err || !user) {
        console.error("Authentication error:", err);
        return res.redirect("/api/login");
      }
      req.logIn(user, (loginErr) => {
        if (loginErr) {
          console.error("Login error:", loginErr);
          return res.redirect("/api/login");
        }
        // Redirect to frontend origin
        return res.redirect(frontendOrigin);
      });
    })(req, res, next);
  });

  app.get("/api/logout", (req, res) => {
    req.logout(() => {
      res.redirect(
        client.buildEndSessionUrl(config, {
          client_id: process.env.REPL_ID,
          post_logout_redirect_uri: frontendOrigin,
        }).href
      );
    });
  });
}

export const isAuthenticated = async (req, res, next) => {
  const user = req.user;

  if (!req.isAuthenticated() || !user || !user.expires_at) {
    return res.status(401).json({ 
      error: "Authentication required",
      message: "Please log in to continue",
      code: "NOT_AUTHENTICATED"
    });
  }

  const now = Math.floor(Date.now() / 1000);
  if (now <= user.expires_at) {
    return next();
  }

  const refreshToken = user.refresh_token;
  if (!refreshToken) {
    return res.status(401).json({ 
      error: "Session expired",
      message: "Your session has expired. Please log in again",
      code: "SESSION_EXPIRED"
    });
  }

  try {
    const config = await getOidcConfig();
    const tokenResponse = await client.refreshTokenGrant(config, refreshToken, {
      client_id: process.env.REPL_ID
    });
    updateUserSession(user, tokenResponse);
    return next();
  } catch (error) {
    console.error("Token refresh failed:", error.message);
    console.error("Token refresh error details:", error);
    return res.status(401).json({ 
      error: "Session expired",
      message: "Your session has expired. Please log in again",
      code: "TOKEN_REFRESH_FAILED"
    });
  }
};
