import * as client from "openid-client";
import { Strategy } from "openid-client/passport";
import passport from "passport";
import session from "express-session";
import { Request, Response, NextFunction, Application } from "express";
import memoize from "memoizee";
import connectPg from "connect-pg-simple";
import { storage } from "./storage.js";
import type { SessionUser, OAuthClaims } from "./express.d.ts";

function getClientId(): string {
  const replId = process.env.REPL_ID;
  if (!replId) {
    console.error('[Auth] REPL_ID is not set. Available env vars:', 
      Object.keys(process.env).filter(k => k.startsWith('REPL') || k.startsWith('REPLIT')).join(', '));
    throw new Error(
      'REPL_ID environment variable is required for OAuth authentication. ' +
      'This should be automatically set by Replit. If you see this error in production, ' +
      'ensure the deployment has access to Replit environment variables.'
    );
  }
  return replId;
}

const getOidcConfig = memoize(
  async () => {
    const clientId = getClientId();
    console.log(`[Auth] Initializing OIDC discovery with client_id: ${clientId.substring(0, 8)}...`);
    try {
      const config = await client.discovery(
        new URL(process.env.ISSUER_URL ?? "https://replit.com/oidc"),
        clientId
      );
      console.log('[Auth] OIDC discovery completed successfully');
      return config;
    } catch (error) {
      console.error('[Auth] OIDC discovery failed:', error);
      throw error;
    }
  },
  { maxAge: 3600 * 1000 }
);

// Shared frontend origin calculation
// This function determines the correct frontend origin for OAuth callbacks and CORS
// Follows Replit guidelines: use REPLIT_DEV_DOMAIN for dev, REPLIT_DOMAINS for production, FRONTEND_ORIGIN env var, or localhost:5000 fallback
export function getFrontendOrigin(): string {
  if (process.env.REPLIT_DEV_DOMAIN) {
    return `https://${process.env.REPLIT_DEV_DOMAIN}`;
  } else if (process.env.REPLIT_DOMAINS) {
    // REPLIT_DOMAINS is comma-separated in production (e.g., "sanchopoetry.com,www.sanchopoetry.com,...")
    // Use the first domain for OAuth callbacks
    const firstDomain = process.env.REPLIT_DOMAINS.split(',')[0].trim();
    return `https://${firstDomain}`;
  } else if (process.env.FRONTEND_ORIGIN) {
    return process.env.FRONTEND_ORIGIN;
  } else {
    return 'http://localhost:5000';
  }
}

export function getSession(): ReturnType<typeof session> {
  // Validate required environment variables
  if (!process.env.SESSION_SECRET) {
    throw new Error(
      'SESSION_SECRET must be set. This is auto-generated by Replit but must be configured for sessions to work.'
    );
  }

  // Validate session secret strength
  const sessionSecret = process.env.SESSION_SECRET;
  const minLength = 32;
  if (sessionSecret.length < minLength) {
    throw new Error(
      `SESSION_SECRET must be at least ${minLength} characters long for security. Current length: ${sessionSecret.length}`
    );
  }

  // Warn if session secret appears to be weak (only alphanumeric or only lowercase)
  const hasUpperCase = /[A-Z]/.test(sessionSecret);
  const hasLowerCase = /[a-z]/.test(sessionSecret);
  const hasNumbers = /[0-9]/.test(sessionSecret);
  const hasSpecialChars = /[^a-zA-Z0-9]/.test(sessionSecret);
  const characterTypeCount = [hasUpperCase, hasLowerCase, hasNumbers, hasSpecialChars].filter(Boolean).length;

  if (characterTypeCount < 3) {
    console.warn(
      'WARNING: SESSION_SECRET should contain at least 3 of: uppercase, lowercase, numbers, special characters for better security.'
    );
  }

  if (!process.env.DATABASE_URL) {
    throw new Error(
      'DATABASE_URL must be set. Sessions require a database connection.'
    );
  }

  const sessionTtl = 7 * 24 * 60 * 60 * 1000; // 1 week
  const pgStore = connectPg(session);
  const sessionStore = new pgStore({
    conString: process.env.DATABASE_URL,
    createTableIfMissing: true, // Auto-create sessions table if missing
    ttl: sessionTtl,
    tableName: "sessions",
  });
  
  // Detect production: either explicit NODE_ENV or Replit production deployment
  // In Replit production deployments: REPLIT_DOMAINS is set but REPLIT_DEV_DOMAIN is not
  const isReplitProduction = Boolean(process.env.REPLIT_DOMAINS && !process.env.REPLIT_DEV_DOMAIN);
  const isProduction = process.env.NODE_ENV === 'production' || isReplitProduction;
  
  console.log(`[Auth] Session configuration - isProduction: ${isProduction}, NODE_ENV: ${process.env.NODE_ENV}, REPLIT_DEV_DOMAIN: ${process.env.REPLIT_DEV_DOMAIN ? 'set' : 'not set'}, REPLIT_DOMAINS: ${process.env.REPLIT_DOMAINS ? 'set' : 'not set'}`);
  
  return session({
    secret: process.env.SESSION_SECRET,
    store: sessionStore,
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: true, // Always secure since Replit uses HTTPS
      sameSite: 'none', // Required for OAuth cross-origin redirects
      maxAge: sessionTtl,
    },
  });
}

function updateUserSession(user: SessionUser, tokens: client.TokenEndpointResponse): void {
  const getClaims = tokens.claims as (() => Record<string, unknown>) | undefined;
  const claims = (getClaims ? getClaims() : {}) as unknown as OAuthClaims;
  user.claims = claims;
  user.access_token = tokens.access_token;
  user.refresh_token = tokens.refresh_token;
  user.expires_at = claims?.exp;
}

async function upsertUser(claims: OAuthClaims): Promise<void> {
  await storage.upsertUser({
    id: claims.sub,
    email: claims.email,
    firstName: claims.first_name,
    lastName: claims.last_name,
    profileImageUrl: claims.profile_image_url,
  });
}

export async function setupAuth(app: Application): Promise<void> {
  app.set("trust proxy", 1);
  app.use(getSession());
  app.use(passport.initialize());
  app.use(passport.session());

  const config = await getOidcConfig();

  const verify = async (tokens: client.TokenEndpointResponse, verified: (err: Error | null, user?: SessionUser) => void): Promise<void> => {
    const user: SessionUser = {};
    updateUserSession(user, tokens);
    const getClaims = tokens.claims as (() => Record<string, unknown>) | undefined;
    const claims = (getClaims ? getClaims() : {}) as unknown as OAuthClaims;
    await upsertUser(claims);
    verified(null, user);
  };

  // Keep track of registered strategies
  const registeredStrategies = new Set();

  // Helper function to ensure strategy exists for a domain
  // Uses req.hostname (just hostname, no port) as required by Replit Auth
  const ensureStrategy = (hostname: string): void => {
    const strategyName = `replitauth:${hostname}`;
    if (!registeredStrategies.has(strategyName)) {
      const strategy = new Strategy(
        {
          name: strategyName,
          config,
          scope: "openid email profile offline_access",
          // Callback URL must match the domain the user is accessing
          callbackURL: `https://${hostname}/api/callback`,
        },
        verify,
      );
      passport.use(strategy);
      registeredStrategies.add(strategyName);
      console.log(`Registered OAuth strategy for: ${hostname}`);
    }
  };

  passport.serializeUser((user: Express.User, cb) => cb(null, user));
  passport.deserializeUser((user: Express.User, cb) => cb(null, user));

  app.get("/api/login", (req, res, next) => {
    // Use req.hostname (not req.get('host')) - hostname without port
    ensureStrategy(req.hostname);
    passport.authenticate(`replitauth:${req.hostname}`, {
      prompt: "login consent",
      scope: ["openid", "email", "profile", "offline_access"],
    })(req, res, next);
  });

  app.get("/api/callback", (req, res, next) => {
    ensureStrategy(req.hostname);
    passport.authenticate(`replitauth:${req.hostname}`, {
      successReturnToOrRedirect: "/",
      failureRedirect: "/api/login",
    })(req, res, next);
  });

  app.get("/api/logout", (req, res) => {
    req.logout(() => {
      res.redirect(
        client.buildEndSessionUrl(config, {
          client_id: getClientId(),
          post_logout_redirect_uri: `${req.protocol}://${req.hostname}`,
        }).href
      );
    });
  });
}

export const isAuthenticated = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  const user = req.user;

  if (!req.isAuthenticated() || !user || !user.expires_at) {
    res.status(401).json({ 
      error: "Authentication required",
      message: "Please log in to continue",
      code: "NOT_AUTHENTICATED"
    });
    return;
  }

  const now = Math.floor(Date.now() / 1000);
  if (now <= user.expires_at) {
    next();
    return;
  }

  const refreshToken = user.refresh_token;
  if (!refreshToken) {
    res.status(401).json({ 
      error: "Session expired",
      message: "Your session has expired. Please log in again",
      code: "SESSION_EXPIRED"
    });
    return;
  }

  try {
    const config = await getOidcConfig();
    const tokenResponse = await client.refreshTokenGrant(config, refreshToken, {
      client_id: getClientId()
    });
    updateUserSession(user as SessionUser, tokenResponse);
    next();
    return;
  } catch (error) {
    const err = error as Error;
    console.error("Token refresh failed:", err.message);
    console.error("Token refresh error details:", error);
    res.status(401).json({ 
      error: "Session expired",
      message: "Your session has expired. Please log in again",
      code: "TOKEN_REFRESH_FAILED"
    });
    return;
  }
};
